error: 
    status - 500 
    message - Error: This Note Already Exists
    at _callee$ (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\src\services\/note.service.js:12:13)
    at tryCatch (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/note/create 
    method - POST 
    IP - ::1
   {"timestamp":"2022-02-23T18:40:38.512Z"}
error: 
    status - 500 
    message - Error: This Note Already Exists
    at _callee$ (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\src\services\/note.service.js:12:13)
    at tryCatch (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/note/create 
    method - POST 
    IP - ::1
   {"timestamp":"2022-02-23T18:40:58.006Z"}
error: 
    status - 500 
    message - Error: This Note Already Exists
    at _callee$ (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\src\services\/note.service.js:12:13)
    at tryCatch (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/note/create 
    method - POST 
    IP - ::1
   {"timestamp":"2022-02-23T18:41:13.441Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-24T02:24:11.454Z"}
info: Connected to the database. {"timestamp":"2022-02-24T02:24:11.488Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-24T02:31:43.987Z"}
info: Connected to the database. {"timestamp":"2022-02-24T02:31:44.011Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-24T02:40:33.812Z"}
info: Connected to the database. {"timestamp":"2022-02-24T02:40:33.851Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-24T02:40:48.902Z"}
info: Connected to the database. {"timestamp":"2022-02-24T02:40:48.932Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-24T02:40:59.945Z"}
info: Connected to the database. {"timestamp":"2022-02-24T02:40:59.980Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-24T02:46:21.506Z"}
info: Connected to the database. {"timestamp":"2022-02-24T02:46:21.539Z"}
error: 
    status - 500 
    message - SyntaxError: Unexpected token { in JSON at position 21
    at JSON.parse (<anonymous>)
    at parse (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\body-parser\lib\types\json.js:89:19)
    at C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\body-parser\lib\read.js:121:18
    at invokeCallback (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\raw-body\index.js:224:16)
    at done (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\raw-body\index.js:213:7)
    at IncomingMessage.onEnd (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\raw-body\index.js:273:7)
    at IncomingMessage.emit (node:events:402:35)
    at IncomingMessage.emit (node:domain:475:12)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) 
    url - /api/v1/note/updatenotes/ 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-02-24T02:58:19.817Z"}
error: 
    status - 500 
    message - SyntaxError: Unexpected token { in JSON at position 45
    at JSON.parse (<anonymous>)
    at parse (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\body-parser\lib\types\json.js:89:19)
    at C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\body-parser\lib\read.js:121:18
    at invokeCallback (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\raw-body\index.js:224:16)
    at done (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\raw-body\index.js:213:7)
    at IncomingMessage.onEnd (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\raw-body\index.js:273:7)
    at IncomingMessage.emit (node:events:402:35)
    at IncomingMessage.emit (node:domain:475:12)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) 
    url - /api/v1/note/deletenotes/?_id=621665e25d0cab319cf7b8ef 
    method - DELETE 
    IP - ::1
   {"timestamp":"2022-02-24T03:02:11.543Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-24T03:07:30.308Z"}
info: Connected to the database. {"timestamp":"2022-02-24T03:07:30.346Z"}
error: 
    status - 500 
    message - SyntaxError: Unexpected token { in JSON at position 45
    at JSON.parse (<anonymous>)
    at parse (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\body-parser\lib\types\json.js:89:19)
    at C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\body-parser\lib\read.js:121:18
    at invokeCallback (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\raw-body\index.js:224:16)
    at done (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\raw-body\index.js:213:7)
    at IncomingMessage.onEnd (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\raw-body\index.js:273:7)
    at IncomingMessage.emit (node:events:402:35)
    at IncomingMessage.emit (node:domain:475:12)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) 
    url - /api/v1/note/?_id=621665e25d0cab319cf7b8ef 
    method - DELETE 
    IP - ::1
   {"timestamp":"2022-02-24T03:08:01.126Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-24T03:13:23.738Z"}
info: Connected to the database. {"timestamp":"2022-02-24T03:13:23.770Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-24T03:14:39.367Z"}
info: Connected to the database. {"timestamp":"2022-02-24T03:14:39.401Z"}
error: 
    status - 500 
    message - SyntaxError: Unexpected token { in JSON at position 45
    at JSON.parse (<anonymous>)
    at parse (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\body-parser\lib\types\json.js:89:19)
    at C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\body-parser\lib\read.js:121:18
    at invokeCallback (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\raw-body\index.js:224:16)
    at done (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\raw-body\index.js:213:7)
    at IncomingMessage.onEnd (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\raw-body\index.js:273:7)
    at IncomingMessage.emit (node:events:402:35)
    at IncomingMessage.emit (node:domain:475:12)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) 
    url - /api/v1/note/getnote 
    method - GET 
    IP - ::1
   {"timestamp":"2022-02-24T05:44:25.235Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-24T05:47:50.785Z"}
info: Connected to the database. {"timestamp":"2022-02-24T05:47:50.823Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-24T05:53:42.677Z"}
info: Connected to the database. {"timestamp":"2022-02-24T05:53:42.745Z"}
info: Connected to the database. {"timestamp":"2022-02-24T05:53:45.561Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-24T05:54:50.744Z"}
info: Connected to the database. {"timestamp":"2022-02-24T05:54:50.778Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-24T05:58:58.147Z"}
info: Connected to the database. {"timestamp":"2022-02-24T05:58:58.189Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-24T05:59:07.570Z"}
info: Connected to the database. {"timestamp":"2022-02-24T05:59:07.658Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-24T05:59:29.777Z"}
info: Connected to the database. {"timestamp":"2022-02-24T05:59:29.839Z"}
error: 
    status - 500 
    message - Error: This Note Already Exists
    at _callee$ (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\src\services\/note.service.js:12:13)
    at tryCatch (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/note/create 
    method - POST 
    IP - ::1
   {"timestamp":"2022-02-24T06:06:13.620Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-24T06:08:28.930Z"}
info: Connected to the database. {"timestamp":"2022-02-24T06:08:28.988Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-24T06:10:35.957Z"}
info: Connected to the database. {"timestamp":"2022-02-24T06:10:35.989Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-24T06:11:39.705Z"}
info: Connected to the database. {"timestamp":"2022-02-24T06:11:39.737Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-24T06:30:18.459Z"}
info: Connected to the database. {"timestamp":"2022-02-24T06:30:18.492Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-24T06:41:19.662Z"}
info: Connected to the database. {"timestamp":"2022-02-24T06:41:19.702Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-24T07:38:44.639Z"}
info: Connected to the database. {"timestamp":"2022-02-24T07:38:44.678Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-24T08:24:21.867Z"}
info: Connected to the database. {"timestamp":"2022-02-24T08:24:21.914Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-24T08:24:55.011Z"}
info: Connected to the database. {"timestamp":"2022-02-24T08:24:55.046Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-24T08:25:14.847Z"}
info: Connected to the database. {"timestamp":"2022-02-24T08:25:14.883Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-24T08:26:39.566Z"}
info: Connected to the database. {"timestamp":"2022-02-24T08:26:39.651Z"}
info: Connected to the database. {"timestamp":"2022-02-24T08:26:41.476Z"}
info: Connected to the database. {"timestamp":"2022-02-24T08:27:28.295Z"}
info: Connected to the database. {"timestamp":"2022-02-24T08:27:53.167Z"}
info: Connected to the database. {"timestamp":"2022-02-24T08:29:14.631Z"}
info: Connected to the database. {"timestamp":"2022-02-24T08:30:59.168Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-24T08:31:33.625Z"}
info: Connected to the database. {"timestamp":"2022-02-24T08:31:33.656Z"}
info: Connected to the database. {"timestamp":"2022-02-24T12:22:12.276Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-24T15:22:30.231Z"}
info: Connected to the database. {"timestamp":"2022-02-24T15:22:30.257Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-24T15:22:46.832Z"}
info: Connected to the database. {"timestamp":"2022-02-24T15:22:46.867Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-24T15:22:58.992Z"}
info: Connected to the database. {"timestamp":"2022-02-24T15:22:59.037Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-24T15:27:20.594Z"}
info: Connected to the database. {"timestamp":"2022-02-24T15:27:20.632Z"}
info: Connected to the database. {"timestamp":"2022-02-24T15:27:21.386Z"}
info: Connected to the database. {"timestamp":"2022-02-24T15:27:45.387Z"}
info: Connected to the database. {"timestamp":"2022-02-24T15:28:44.738Z"}
info: Connected to the database. {"timestamp":"2022-02-24T15:28:58.394Z"}
info: Connected to the database. {"timestamp":"2022-02-24T15:29:40.800Z"}
info: Connected to the database. {"timestamp":"2022-02-24T15:37:42.858Z"}
info: Connected to the database. {"timestamp":"2022-02-24T15:40:53.378Z"}
info: Connected to the database. {"timestamp":"2022-02-24T15:41:08.604Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-24T15:41:59.564Z"}
info: Connected to the database. {"timestamp":"2022-02-24T15:41:59.594Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-24T15:53:59.256Z"}
info: Connected to the database. {"timestamp":"2022-02-24T15:53:59.289Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-24T15:56:55.774Z"}
info: Connected to the database. {"timestamp":"2022-02-24T15:56:55.871Z"}
info: Connected to the database. {"timestamp":"2022-02-24T15:57:04.619Z"}
info: Connected to the database. {"timestamp":"2022-02-24T15:57:08.720Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-24T16:02:27.679Z"}
info: Connected to the database. {"timestamp":"2022-02-24T16:02:27.719Z"}
error: 
    status - 500 
    message - Error: password is invalid
    at _callee3$ (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\src\services\/user.service.js:33:13)
    at tryCatch (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-02-24T16:08:45.563Z"}
error: 
    status - 500 
    message - ReferenceError: searchData is not defined
    at _callee3$ (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\src\services\/user.service.js:29:41)
    at tryCatch (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-02-24T16:08:54.090Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-24T16:11:57.726Z"}
info: Connected to the database. {"timestamp":"2022-02-24T16:11:57.808Z"}
error: 
    status - 500 
    message - ReferenceError: searchData is not defined
    at _callee3$ (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\src\services\/user.service.js:29:41)
    at tryCatch (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-02-24T16:13:55.468Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-24T16:29:00.042Z"}
info: Connected to the database. {"timestamp":"2022-02-24T16:29:00.080Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-24T16:29:09.454Z"}
info: Connected to the database. {"timestamp":"2022-02-24T16:29:09.487Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-24T16:29:46.579Z"}
info: Connected to the database. {"timestamp":"2022-02-24T16:29:46.611Z"}
error: 
    status - 500 
    message - Error: The boolean type does not allow arguments
    at new module.exports (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\@hapi\hoek\lib\error.js:23:19)
    at module.exports (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\@hapi\hoek\lib\assert.js:20:11)
    at Object.Joi (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\@hapi\joi\lib\index.js:57:13)
    at newNoteValidator (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\src\validators\/user.validator.js:26:17)
    at Layer.handle [as handle_request] (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\express\lib\router\index.js:341:12)
    at next (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\express\lib\router\index.js:174:3)
    at router (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\express\lib\router\index.js:323:13)
    at C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\express\lib\router\index.js:284:7 
    url - /api/v1/note/create 
    method - POST 
    IP - ::1
   {"timestamp":"2022-02-24T17:38:39.449Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-24T17:39:56.358Z"}
info: Connected to the database. {"timestamp":"2022-02-24T17:39:56.424Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-24T17:40:08.141Z"}
info: Connected to the database. {"timestamp":"2022-02-24T17:40:08.191Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-24T17:40:49.352Z"}
info: Connected to the database. {"timestamp":"2022-02-24T17:40:49.384Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-24T17:41:04.643Z"}
info: Connected to the database. {"timestamp":"2022-02-24T17:41:04.701Z"}
error: 
    status - 500 
    message - Error: The boolean type does not allow arguments
    at new module.exports (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\@hapi\hoek\lib\error.js:23:19)
    at module.exports (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\@hapi\hoek\lib\assert.js:20:11)
    at Object.Joi (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\@hapi\joi\lib\index.js:57:13)
    at newNoteValidator (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\src\validators\/user.validator.js:26:17)
    at Layer.handle [as handle_request] (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\express\lib\router\index.js:341:12)
    at next (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\express\lib\router\index.js:174:3)
    at router (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\express\lib\router\index.js:323:13)
    at C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\express\lib\router\index.js:284:7 
    url - /api/v1/note/create 
    method - POST 
    IP - ::1
   {"timestamp":"2022-02-24T17:41:10.034Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-24T17:42:53.840Z"}
info: Connected to the database. {"timestamp":"2022-02-24T17:42:53.869Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-24T17:43:54.004Z"}
info: Connected to the database. {"timestamp":"2022-02-24T17:43:54.106Z"}
error: 
    status - 500 
    message - Error: The boolean type does not allow arguments
    at new module.exports (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\@hapi\hoek\lib\error.js:23:19)
    at module.exports (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\@hapi\hoek\lib\assert.js:20:11)
    at Object.Joi (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\@hapi\joi\lib\index.js:57:13)
    at newNoteValidator (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\src\validators\/user.validator.js:26:17)
    at Layer.handle [as handle_request] (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\express\lib\router\index.js:341:12)
    at next (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\express\lib\router\index.js:174:3)
    at router (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\express\lib\router\index.js:323:13)
    at C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\express\lib\router\index.js:284:7 
    url - /api/v1/note/create 
    method - POST 
    IP - ::1
   {"timestamp":"2022-02-24T17:44:20.549Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-24T17:45:32.050Z"}
info: Connected to the database. {"timestamp":"2022-02-24T17:45:32.082Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-24T17:46:41.600Z"}
info: Connected to the database. {"timestamp":"2022-02-24T17:46:41.640Z"}
error: 
    status - 500 
    message - Error: This Note Already Exists
    at _callee$ (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\src\services\/note.service.js:12:15)
    at tryCatch (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/note 
    method - POST 
    IP - ::1
   {"timestamp":"2022-02-24T17:46:52.472Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-24T17:50:05.978Z"}
info: Connected to the database. {"timestamp":"2022-02-24T17:50:06.010Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-24T18:23:45.281Z"}
info: Connected to the database. {"timestamp":"2022-02-24T18:23:45.311Z"}
